#!/bin/bash

if [[ $1 != clean ]]
then
	echo "Generating documentation ..."
	doxygen Doxyfile
	if [[ $? == 0 ]]
	then
		echo "Open doc/html/index.html in your web browser!"
	fi
else
	rm -rf doc/html/
fi
