"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"\t<meta charset=\"iso-8859-1\" />\n"
"\t<link rel=\"stylesheet\" href=\"style.css\" type=\"text/css\" />\n"
"\t<title>Bare metal Webserver</title>\n"
"</head>\n"
"<body>\n"
"\t<h1>Bare metal Webserver</h1>\n"
"\n"
"\t<p>You can switch the Act LED with this form.</p>\n"
"\n"
"\t<!-- Specify enctype to be sure it can be handled. -->\n"
"\t<form action=\"index.html\" method=\"post\" enctype=\"application/x-www-form-urlencoded\">\n"
"\t\t<table>\n"
"\t\t<tr>\n"
"\t\t\t<th colspan=\"3\">Act LED status</th>\n"
"\t\t</tr>\n"
"\t\t<tr>\n"
"\t\t\t<td><input type=\"radio\" name=\"actled\" value=\"0\" %s />Off</td>\n"
"\t\t\t<td><input type=\"radio\" name=\"actled\" value=\"1\" %s />On</td>\n"
"\t\t\t<td><img src=\"%s\" alt=\"Act LED\" /></td>\n"
"\t\t</tr>\n"
"\t\t<tr>\n"
"\t\t\t<td colspan=\"3\"><input type=\"submit\" value=\"OK\" /></td>\n"
"\t\t</tr>\n"
"\t\t</table>\n"
"\t</form>\n"
"\n"
"\t<hr />\n"
"\t<p class=\"small\">Based on the <a href=\"https://github.com/rsta2/circle\" target=\"_blank\">Circle</a> C++ bare metal environment.</p>\n"
"</body>\n"
"</html>\n"
""