# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Publish to Github Packages

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    # (Restrict) Permissions for GITHUB_TOKEN
    # permissions:
    #   contents: read
    #   packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'yarn'
    - name: Setup Yarn
      run: |
        yarn config set npmScopes.ncoderz.npmRegistryServer "https://npm.pkg.github.com"
        yarn config set npmScopes.ncoderz.npmPublishRegistry "https://npm.pkg.github.com"
        yarn config set npmScopes.ncoderz.npmAlwaysAuth true
        yarn config set npmScopes.ncoderz.npmAuthToken $GITHUB_AUTH_TOKEN
      env:
        GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: yarn install --immutable
    - name: Publish
      run: yarn npm publish
