#
# Makefile
#

CIRCLEHOME = ../..

OBJS	= main.o kernel.o mandelbrot.o temptask.o

LIBS	= $(CIRCLEHOME)/lib/sched/libsched$(RASPPI).a \
	  $(CIRCLEHOME)/lib/libcircle$(RASPPI).a

include ../Rules.mk
