// Normal	Shift		AltGr
{KeyNone,	KeyNone,	KeyNone},	// 0x00
{KeyNone,	KeyNone,	KeyNone},	// 0x01
{KeyNone,	KeyNone,	KeyNone},	// 0x02
{KeyNone,	KeyNone,	KeyNone},	// 0x03
{'a',		'A',		KeyNone},	// 0x04
{'b',		'B',		KeyNone},	// 0x05
{'c',		'C',		KeyNone},	// 0x06
{'d',		'D',		KeyNone},	// 0x07
{'e',		'E',		KeyNone},	// 0x08
{'f',		'F',		KeyNone},	// 0x09
{'g',		'G',		KeyNone},	// 0x0A
{'h',		'H',		KeyNone},	// 0x0B
{'i',		'I',		KeyNone},	// 0x0C
{'j',		'J',		KeyNone},	// 0x0D
{'k',		'K',		KeyNone},	// 0x0E
{'l',		'L',		KeyNone},	// 0x0F
{'m',		'M',		KeyNone},	// 0x10
{'n',		'N',		KeyNone},	// 0x11
{'o',		'O',		KeyNone},	// 0x12
{'p',		'P',		KeyNone},	// 0x13
{'q',		'Q',		KeyNone},	// 0x14
{'r',		'R',		KeyNone},	// 0x15
{'s',		'S',		KeyNone},	// 0x16
{'t',		'T',		KeyNone},	// 0x17
{'u',		'U',		KeyNone},	// 0x18
{'v',		'V',		KeyNone},	// 0x19
{'w',		'W',		KeyNone},	// 0x1A
{'x',		'X',		KeyNone},	// 0x1B
{'y',		'Y',		KeyNone},	// 0x1C
{'z',		'Z',		KeyNone},	// 0x1D
{'1',		'!',		KeyNone},	// 0x1E
{'2',		'\"',		KeyNone},	// 0x1F
{'3',		KeyNone,	KeyNone},	// 0x20
{'4',		'$',		KeyNone},	// 0x21
{'5',		'%',		KeyNone},	// 0x22
{'6',		'^',		KeyNone},	// 0x23
{'7',		'&',		KeyNone},	// 0x24
{'8',		'*',		KeyNone},	// 0x25
{'9',		'(',		KeyNone},	// 0x26
{'0',		')',		KeyNone},	// 0x27
{KeyReturn,	KeyReturn,	KeyNone},	// 0x28
{KeyEscape,	KeyEscape,	KeyNone},	// 0x29
{KeyBackspace,	KeyBackspace,	KeyNone},	// 0x2A
{KeyTabulator,	KeyTabulator,	KeyNone},	// 0x2B
{KeySpace,	KeySpace,	KeyNone},	// 0x2C
{'-',		'_',		KeyNone},	// 0x2D
{'=',		'+',		KeyNone},	// 0x2E
{'[',		'{',		KeyNone},	// 0x2F
{']',		'}',		KeyNone},	// 0x30
{'\\',		'|',		KeyNone},	// 0x31
{'#',		'~',		KeyNone},	// 0x32
{';',		':',		KeyNone},	// 0x33
{'\'',		'@',		KeyNone},	// 0x34
{'`',		KeyNone,	'|'}	,	// 0x35
{',',		'<',		KeyNone},	// 0x36
{'.',		'>',		KeyNone},	// 0x37
{'/',		'?',		KeyNone},	// 0x38
{KeyCapsLock,	KeyCapsLock,	KeyNone},	// 0x39
{KeyF1,		KeyNone,	KeyNone},	// 0x3A
{KeyF2,		KeyNone,	KeyNone},	// 0x3B
{KeyF3,		KeyNone,	KeyNone},	// 0x3C
{KeyF4,		KeyNone,	KeyNone},	// 0x3D
{KeyF5,		KeyNone,	KeyNone},	// 0x3E
{KeyF6,		KeyNone,	KeyNone},	// 0x3F
{KeyF7,		KeyNone,	KeyNone},	// 0x40
{KeyF8,		KeyNone,	KeyNone},	// 0x41
{KeyF9,		KeyNone,	KeyNone},	// 0x42
{KeyF10,	KeyNone,	KeyNone},	// 0x43
{KeyF11,	KeyNone,	KeyNone},	// 0x44
{KeyF12,	KeyNone,	KeyNone},	// 0x45
{KeyPrintScreen,KeyNone,	KeyNone},	// 0x46
{KeyScrollLock,	KeyNone,	KeyNone},	// 0x47
{KeyPause,	KeyNone,	KeyNone},	// 0x48
{KeyInsert,	KeyNone,	KeyNone},	// 0x49
{KeyHome,	KeyNone,	KeyNone},	// 0x4A
{KeyPageUp,	KeyNone,	KeyNone},	// 0x4B
{KeyDelete,	KeyNone,	KeyNone},	// 0x4C
{KeyEnd,	KeyNone,	KeyNone},	// 0x4D
{KeyPageDown,	KeyNone,	KeyNone},	// 0x4E
{KeyRight,	KeyNone,	KeyNone},	// 0x4F
{KeyLeft,	KeyNone,	KeyNone},	// 0x50
{KeyDown,	KeyNone,	KeyNone},	// 0x51
{KeyUp,		KeyNone,	KeyNone},	// 0x52
{KeyNumLock,	KeyNumLock,	KeyNone},	// 0x53
{KeyKP_Divide,	KeyKP_Divide,	KeyNone},	// 0x54
{KeyKP_Multiply,KeyKP_Multiply,	KeyNone},	// 0x55
{KeyKP_Subtract,KeyKP_Subtract,	KeyNone},	// 0x56
{KeyKP_Add,	KeyKP_Add,	KeyNone},	// 0x57
{KeyKP_Enter,	KeyKP_Enter,	KeyNone},	// 0x58
{KeyEnd,	KeyKP_1,	KeyNone},	// 0x59
{KeyDown,	KeyKP_2,	KeyNone},	// 0x5A
{KeyPageDown,	KeyKP_3,	KeyNone},	// 0x5B
{KeyLeft,	KeyKP_4,	KeyNone},	// 0x5C
{KeyKP_Center,	KeyKP_5,	KeyNone},	// 0x5D
{KeyRight,	KeyKP_6,	KeyNone},	// 0x5E
{KeyHome,	KeyKP_7,	KeyNone},	// 0x5F
{KeyUp,		KeyKP_8,	KeyNone},	// 0x60
{KeyPageUp,	KeyKP_9,	KeyNone},	// 0x61
{KeyInsert,	KeyKP_0,	KeyNone},	// 0x62
{KeyDelete,	KeyKP_Period,	KeyNone},	// 0x63
{'\\',		'|',		KeyNone},	// 0x64
{KeyApplication,KeyApplication,	KeyNone},	// 0x65
{KeyNone,	KeyNone,	KeyNone},	// 0x66
{KeyNone,	KeyNone,	KeyNone},	// 0x67
{KeyNone,	KeyNone,	KeyNone},	// 0x68
{KeyNone,	KeyNone,	KeyNone},	// 0x69
{KeyNone,	KeyNone,	KeyNone},	// 0x6A
{KeyNone,	KeyNone,	KeyNone},	// 0x6B
{KeyNone,	KeyNone,	KeyNone},	// 0x6C
{KeyNone,	KeyNone,	KeyNone},	// 0x6D
{KeyNone,	KeyNone,	KeyNone},	// 0x6E
{KeyNone,	KeyNone,	KeyNone},	// 0x6F
{KeyNone,	KeyNone,	KeyNone},	// 0x70
{KeyNone,	KeyNone,	KeyNone},	// 0x71
{KeyNone,	KeyNone,	KeyNone},	// 0x72
{KeyNone,	KeyNone,	KeyNone},	// 0x73
{KeyNone,	KeyNone,	KeyNone},	// 0x74
{KeyNone,	KeyNone,	KeyNone},	// 0x75
{KeyNone,	KeyNone,	KeyNone},	// 0x76
{KeyNone,	KeyNone,	KeyNone},	// 0x77
{KeyNone,	KeyNone,	KeyNone},	// 0x78
{KeyNone,	KeyNone,	KeyNone},	// 0x79
{KeyNone,	KeyNone,	KeyNone},	// 0x7A
{KeyNone,	KeyNone,	KeyNone},	// 0x7B
{KeyNone,	KeyNone,	KeyNone},	// 0x7C
{KeyNone,	KeyNone,	KeyNone},	// 0x7D
{KeyNone,	KeyNone,	KeyNone},	// 0x7E
{KeyNone,	KeyNone,	KeyNone}	// 0x7F
