#!/bin/bash

make="${MAKE:-make}"

cd ..
./makeall $1 $2 || exit

cd addon

## Following required for WLAN

cd fatfs
$make $1 $2 || exit
cd ..

cd SDCard
$make $1 $2 || exit
cd ..

cd wlan
./makeall $1 $2 || exit
cd ..

## Following required for OpenGL ES

cd linux
$make $1 $2 || exit
cd ..

cd vc4
./makeall $1 $2 || exit
cd ..

# cd vc4/vchiq
# $make $1 $2 || exit
# cd ../..

cd vc4/interface
./makeall $1 $2 || exit
cd ../..


cd ../app
