// Normal	Shift		AltGr		AltGr+Shift
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x00
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x01
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x02
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x03
{'a',		'A',		C('\xE1'),	C('\xC1'), KeyNone},	// 0x04
{'b',		'B',		KeyNone,	KeyNone,	KeyNone},	// 0x05
{'c',		'C',		C('\xA9'),	C('\xA2'), KeyNone},	// 0x06
{'d',		'D',		C('\xF0'),	C('\xD0'), KeyNone},	// 0x07
{'e',		'E',		C('\xE9'),	C('\xC9'), KeyNone},	// 0x08
{'f',		'F',		KeyNone,	KeyNone,	KeyNone},	// 0x09
{'g',		'G',		KeyNone,	KeyNone,	KeyNone},	// 0x0A
{'h',		'H',		KeyNone,	KeyNone,	KeyNone},	// 0x0B
{'i',		'I',		C('\xED'),	C('\xCD'), KeyNone},	// 0x0C
{'j',		'J',		KeyNone,	KeyNone,	KeyNone},	// 0x0D
{'k',		'K',		KeyNone,	KeyNone,	KeyNone},	// 0x0E
{'l',		'L',		C('\xF8'),	C('\xD8'), KeyNone},	// 0x0F
{'m',		'M',		C('\xB5'),	KeyNone,	KeyNone},	// 0x10
{'n',		'N',		C('\xF1'),	C('\xD1'), KeyNone},	// 0x11
{'o',		'O',		C('\xF3'),	C('\xD3'), KeyNone},	// 0x12
{'p',		'P',		C('\xF6'),	C('\xD6'), KeyNone},	// 0x13
{'q',		'Q',		C('\xE4'),	C('\xC4'), KeyNone},	// 0x14
{'r',		'R',		C('\xAE'),	KeyNone,	KeyNone},	// 0x15
{'s',		'S',		C('\xDF'),	C('\xA7'), KeyNone},	// 0x16
{'t',		'T',		C('\xFE'),	C('\xDE'), KeyNone},	// 0x17
{'u',		'U',		C('\xFA'),	C('\xDA'), KeyNone},	// 0x18
{'v',		'V',		KeyNone,	KeyNone,	KeyNone},	// 0x19
{'w',		'W',		C('\xE5'),	C('\xC5'), KeyNone},	// 0x1A
{'x',		'X',		KeyNone,	KeyNone,	KeyNone},	// 0x1B
{'y',		'Y',		C('\xFC'),	C('\xDC'), KeyNone},	// 0x1C
{'z',		'Z',		C('\xE6'),	C('\xC6'), KeyNone},	// 0x1D
{'1',		'!',		C('\xA1'),	C('\xB9'), KeyNone},	// 0x1E
{'2',		'@',		C('\xB2'),	KeyNone,	KeyNone},	// 0x1F
{'3',		'#',		C('\xB3'),	KeyNone,	KeyNone},	// 0x20
{'4',		'$',		C('\xA4'),	C('\xA3'), KeyNone},	// 0x21
{'5',		'%',		C('\x80'),	KeyNone,	KeyNone},	// 0x22
{'6',		'^',		C('\xBC'),	KeyNone,	KeyNone},	// 0x23
{'7',		'&',		C('\xBD'),	KeyNone,	KeyNone},	// 0x24
{'8',		'*',		C('\xBE'),	KeyNone,	KeyNone},	// 0x25
{'9',		'(',		KeyNone,	KeyNone,	KeyNone},	// 0x26
{'0',		')',		KeyNone,	KeyNone,	KeyNone},	// 0x27
{KeyReturn,	KeyReturn,	KeyNone,	KeyNone,	KeyNone},	// 0x28
{KeyEscape,	KeyEscape,	KeyNone,	KeyNone,	KeyNone},	// 0x29
{KeyBackspace,	KeyBackspace,	KeyNone,	KeyNone,	KeyNone},	// 0x2A
{KeyTabulator,	KeyTabulator,	KeyNone,	KeyNone,	KeyNone},	// 0x2B
{KeySpace,	KeySpace,	KeyNone,	KeyNone,	KeyNone},	// 0x2C
{'-',		'_',		C('\xA5'),	KeyNone,	KeyNone},	// 0x2D
{'=',		'+',		C('\xD7'),	C('\xF7'), KeyNone},	// 0x2E
{'[',		'{',		C('\xAB'),	KeyNone,	KeyNone},	// 0x2F
{']',		'}',		C('\xBB'),	KeyNone,	KeyNone},	// 0x30
{'\\',		'|',		C('\xAC'),	C('\xA6'), KeyNone},	// 0x31
{'#',		'~',		KeyNone,	KeyNone,	KeyNone},	// 0x32
{';',		':',		C('\xB6'),	C('\xB0'), KeyNone},	// 0x33
{'\'',		'\"',		C('\xB4'),	C('\xA8'), KeyNone},	// 0x34
{'`',		'~',		KeyNone,	KeyNone,	KeyNone},	// 0x35
{',',		'<',		C('\xE7'),	C('\xC7'), KeyNone},	// 0x36
{'.',		'>',		KeyNone,	KeyNone,	KeyNone},	// 0x37
{'/',		'?',		C('\xBF'),	KeyNone,	KeyNone},	// 0x38
{KeyCapsLock,	KeyCapsLock,	KeyNone,	KeyNone,	KeyNone},	// 0x39
{KeyF1,		KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x3A
{KeyF2,		KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x3B
{KeyF3,		KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x3C
{KeyF4,		KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x3D
{KeyF5,		KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x3E
{KeyF6,		KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x3F
{KeyF7,		KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x40
{KeyF8,		KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x41
{KeyF9,		KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x42
{KeyF10,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x43
{KeyF11,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x44
{KeyF12,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x45
{KeyPrintScreen,KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x46
{KeyScrollLock,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x47
{KeyPause,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x48
{KeyInsert,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x49
{KeyHome,	KeyNone,	KeyNone,	KeyNone,	KeyCtrlHome},	// 0x4A
{KeyPageUp,	KeyNone,	KeyNone,	KeyNone,	KeyCtrlPageUp},	// 0x4B
{KeyDelete,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x4C
{KeyEnd,	KeyNone,	KeyNone,	KeyNone,	KeyCtrlEnd},	// 0x4D
{KeyPageDown,	KeyNone,	KeyNone,	KeyNone,	KeyCtrlPageDown},	// 0x4E
{KeyRight,	KeyNone,	KeyNone,	KeyNone,	KeyCtrlRight},	// 0x4F
{KeyLeft,	KeyNone,	KeyNone,	KeyNone,	KeyCtrlLeft},	// 0x50
{KeyDown,	KeyNone,	KeyNone,	KeyNone,	KeyCtrlDown},	// 0x51
{KeyUp,		KeyNone,	KeyNone,	KeyNone,	KeyCtrlUp},	// 0x52
{KeyNumLock,	KeyNumLock,	KeyNone,	KeyNone,	KeyNone},	// 0x53
{KeyKP_Divide,	KeyKP_Divide,	KeyNone,	KeyNone,	KeyNone},	// 0x54
{KeyKP_Multiply,KeyKP_Multiply,	KeyNone,	KeyNone,	KeyNone},	// 0x55
{KeyKP_Subtract,KeyKP_Subtract,	KeyNone,	KeyNone,	KeyNone},	// 0x56
{KeyKP_Add,	KeyKP_Add,	KeyNone,	KeyNone,	KeyNone},	// 0x57
{KeyKP_Enter,	KeyKP_Enter,	KeyNone,	KeyNone,	KeyNone},	// 0x58
{KeyEnd,	KeyKP_1,	KeyNone,	KeyNone,	KeyCtrlEnd},	// 0x59
{KeyDown,	KeyKP_2,	KeyNone,	KeyNone,	KeyNone},	// 0x5A
{KeyPageDown,	KeyKP_3,	KeyNone,	KeyNone,	KeyCtrlPageDown},	// 0x5B
{KeyLeft,	KeyKP_4,	KeyNone,	KeyNone,	KeyNone},	// 0x5C
{KeyKP_Center,	KeyKP_5,	KeyNone,	KeyNone,	KeyNone},	// 0x5D
{KeyRight,	KeyKP_6,	KeyNone,	KeyNone,	KeyNone},	// 0x5E
{KeyHome,	KeyKP_7,	KeyNone,	KeyNone,	KeyCtrlHome},	// 0x5F
{KeyUp,		KeyKP_8,	KeyNone,	KeyNone,	KeyNone},	// 0x60
{KeyPageUp,	KeyKP_9,	KeyNone,	KeyNone,	KeyCtrlPageUp},	// 0x61
{KeyInsert,	KeyKP_0,	KeyNone,	KeyNone,	KeyNone},	// 0x62
{KeyDelete,	KeyKP_Period,	KeyNone,	KeyNone,	KeyNone},	// 0x63
{'\\',		'|',		KeyNone,	KeyNone,	KeyNone},	// 0x64
{KeyApplication,KeyApplication,	KeyNone,	KeyNone,	KeyNone},	// 0x65
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x66
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x67
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x68
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x69
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x6A
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x6B
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x6C
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x6D
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x6E
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x6F
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x70
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x71
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x72
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x73
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x74
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x75
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x76
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x77
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x78
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x79
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x7A
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x7B
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x7C
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x7D
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone},	// 0x7E
{KeyNone,	KeyNone,	KeyNone,	KeyNone,	KeyNone}	// 0x7F
