#
# Makefile
#

CIRCLEHOME = ../../../..

OBJS	= main.o kernel.o 

LIBS	= $(CIRCLEHOME)/addon/WS28XX/libws28xx.a \
	  $(CIRCLEHOME)/lib/libcircle.a

include $(CIRCLEHOME)/sample/Rules.mk

-include $(DEPS)
