#!/bin/bash

make="${MAKE:-make}"

makekhronos=true
if [[ $1 == "--nokhronos" ]]
then
	makekhronos=false
	shift
fi

cd vcos
$make $1 $2 || exit
cd ..

cd vmcs_host
$make $1 $2 || exit
cd ..

if [[ $makekhronos == true ]]
then
	cd khronos
	$make $1 $2 || exit
	cd ..
fi

cd bcm_host
$make $1 $2 || exit
cd ..
