nodeLinker: node-modules

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  ncoderz:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.2.4.cjs
